/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL481_Hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFoundMostFrequentItem() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 2, 4));
        assertEquals(2, App.findMostFrequentItem(array, 1,2,4));
    }

    @Test
    public void testNotFoundMostFrequentItem() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertEquals(1, App.findMostFrequentItem(array, 1, 2, 3));
    }
    @Test
    public void testEmptyArray() {
        ArrayList<Integer> array = new ArrayList<>();
        
        assertThrows(IllegalArgumentException.class, ()->{
            App.findMostFrequentItem(array, 1, 2, 3);
        });
    }
    @Test
    public void testNull() {
        ArrayList<Integer> array = null;
        assertThrows(IllegalArgumentException.class, ()->{
            App.findMostFrequentItem(array, 1, 2, 3);
        });
    }

    @Test
    public void elementIsNotOnTheList() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertThrows(IllegalArgumentException.class, ()->{
            App.findMostFrequentItem(array, 1, 2, 10);
        });
    }

    @Test
    public void elementIsNotPositiveInteger() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertThrows(IllegalArgumentException.class, ()->{
            App.findMostFrequentItem(array, 1, -2, 3);
        });
    }
}
